#include <Eigen/Dense>
#include <Eigen/Geometry>
#include <filesystem>
#include <istream>
#include <sstream>
#include <vector>
#include <string>
#define LUISA_ENABLE_DSL
#include <luisa/luisa-compute.h>